### ISSUE TITLE
Amplify Console does not update lambda layer

### ISSUE THREAD

**Issue by j-yamamoto** [aws-amplify/amplify-hosting#1221]
** Please describe which feature you have a question about? **

Amplify Console CI/CD (Backend)

** Provide additional details**

Amplify Console creates lambda layer successfully on first deployment. However, after the second deployment, it does not update lambda layer although I update the lambda layer source. (I have also updated package.json in lib/nodejs, but Amplify Console did not detect any change in the lambda layer)

**Comment by kahdojay** [comment]
@j-yamamoto can you provide you app id and region, the affected branch(es), and example job numbers? Please also provide steps to reproduce with expected behavior.

**Comment by j-yamamoto** [comment]
Hi, @kahdojay. Unfortunately, I cannot share my app information because I would like to keep it private. 
But, here is the steps for reproduction. Let's say your branch on Github is already connected to your Amplify Console app.

1. Add lambda layer resource with amplify cli
1. Add lambda function resource and attach the lambda layer to it with amplify cli
1. Run amplify push
1. Commit changes on git and run git push (to run CI/CD on Amplify Console)
1. After Amplify Console deploy finishes, update and push the lambda layer again on your local machine
1. Commit changes on git and run git push
1. The second Amplify Console deploy finishes, but a new lambda layer version is not created.


I also asked the same question to the AWS support, and I got an answer that you need to tweek amplify.yml like below.

```
- amplifyPush --simple
# Reset auto generated parameters and cfn template
- git checkout amplify/backend/function/[Your Layer Name]/parameters.json
- git checkout amplify/backend/function/[Your Layer Name]/[Your Layer Name]-awscloudformation-template.json
# Amplify push again
- amplify push --yes
```

**Comment by kahdojay** [comment]
@j-yamamoto you can email the info to aws-amplify-customer@amazon.com

**Comment by contractorwolf** [comment]
dude, I am seeing the same thing, I had an error in my code in the layer.  I updated the code in the layer, pushed up, then update the function that uses the layer to the next version and amplify pushed the function up.  Both layer and function are updated in the cloud and I rerun the function and I still get the same error from the previous version of the layer (not the recent updated version of the layer.

My stuff is more of a research project, so it is not using a secure data so you can take a look:
arn:aws:lambda:us-east-1:237169730438:function:newsarticlepublisherscrape-dev

any advice would be appreciated!

**Comment by akash87** [comment]
@kahdojay - just do a app deployment and connect ci/cd. make any changes to git repo (layer function) - the changes are not reflected.

**Comment by akash87** [comment]
The problem is also reported here - https://github.com/aws-amplify/amplify-cli/issues/6100#issuecomment-747578078

**Comment by contractorwolf** [comment]
I ended up just blowing away the function and re-adding it which solve the problem, but still something was def broken in the amplify process which didnt seem to see my changes.  Sorted for me now though, but not necessarily a good solve.

**Comment by waynebrantley** [comment]
This still happens, reported by multiple people and easily reproducible.
Any update @kahdojay

**Comment by georgeleeventures** [comment]
I'm having the same issue. Can someone please advise? It sounds like the only solution is to run amplify push from the local terminal instead of pushing to git and hoping that amplify picks it up.

**Comment by bourkison** [comment]
Is there any update/solve for this one? My layer is not being updated even when running amplify push in the local terminal.

**Comment by difsta** [comment]
Is there any update on this?

**Comment by elizeire** [comment]
I fixed by doing search and replace at cloudformation template files, and after I had to run 
`amplify update api`

Following all steps but changing nothing, just confirming previous entries..

`amplify push`

done

**Comment by hloriana** [comment]
This issue has been resolved.
