### ISSUE TITLE
SSR resources are not deleted after PR is merged/closed before preview build completion

### ISSUE THREAD

**Issue by asumvp** [aws-amplify/amplify-hosting#2424]
### Before opening, please confirm:

- [x] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Amplify Console feature

Previews

### Describe the bug

Hi Team, If I close/merge the PR after preview build completes, all the SSR resources are deleted after some time. However, on closing/merging the PR while the preview build is running, SSR resources are not deleted even though preview disappear/deleted from the Amplify console.

### Expected behavior

Every time a preview is deleted from Amplify console, all the corresponding SSR resources should also be deleted irrespective of closing/merging the PR before/after the build completion.

### Reproduction steps

1. Associate the amplify app to GitHub.
2. Enable preview.
3. Submit a PR and preview build will start. 
4. close/merge the PR before preview build completes.

**Comment by hloriana** [comment]
Hi @asumvp 👋🏽 Thanks for raising this issue. This is a bug that the team is currently tracking. In the mean time, you'll have to manually delete those resources. I will update this issue once a fix has been rolled out.

**Comment by arbass22** [comment]
My company is likely to move off of Amplify as a result of this issue, any updates @hloriana?

**Comment by hloriana** [comment]
@arbass22 The service team is currently working on this. I do not have an exact date for when the fix will be rolled out but this bug is being treated as a top priority.

**Comment by Alek-S** [comment]
@hloriana do you happen to know if we are being charged for these undelete services resulting from this bug, and if so, will the accounts be credited back that amount?

Also, although I do appreciate there is not an exact date being that it is a bug, seeing as this has been an open defect with the AWS dev team for four months at the time of writing, loosely speaking are we days, weeks, or months away? If it's months away, is there a faster interim solution to be offered to more quickly identify undelete services?

The reason I'm asking is that we are going to start a larger project in approximately a month to a month and a half time, and if it's anticipated to not be resolved by then we need to begin consideration of alternative hosting options.

**Comment by vandreleal** [comment]
Hi @hloriana, any updates on this matter? Thank you for providing feedback on all GH issues created highlighting this issue. My team is facing the same issue on a product we are working on at the moment, which is a monorepo with 2 SSR projects that have staging and production environments with preview links enabled. That has been a cause of concern because each build left behind leaves the following resources that need manual action.

Preview links for MRs
- 6 IAM roles, 2 CF distributions and 2 buckets
Staging / Production
- 12 IAM roles, 4 CF distributions and 4 buckets

**Comment by Alek-S** [comment]
@hloriana 

Got contacted by our manager due to a developer with a failed PR preview build due to maxed-out lambdas occurring again last Friday when I was on PTO so they were left stuck.

```
2022-04-08T20:29:11.812Z [ERROR]: TooManyDistributionsWithLambdaAssociations: Completing this action would cause the maximum number of distributions with Lambda function associations per owner to be exceeded (maximum allowed is 25).
                                  at Request.extractError (/root/.//node_modules/@sls-next/aws-cloudfront/node_modules/aws-sdk/lib/protocol/rest_xml.js:53:29)
                                  at Request.callListeners (/root/.//node_modules/@sls-next/aws-cloudfront/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
                                  at Request.emit (/root/.//node_modules/@sls-next/aws-cloudfront/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
                                  at Request.emit (/root/.//node_modules/@sls-next/aws-cloudfront/node_modules/aws-sdk/lib/request.js:686:14)
                                  at Request.transition (/root/.//node_modules/@sls-next/aws-cloudfront/node_modules/aws-sdk/lib/request.js:22:10)
                                  at AcceptorStateMachine.runTo (/root/.//node_modules/@sls-next/aws-cloudfront/node_modules/aws-sdk/lib/state_machine.js:14:12)
                                  at /root/.//node_modules/@sls-next/aws-cloudfront/node_modules/aws-sdk/lib/state_machine.js:26:10
                                  at Request.<anonymous> (/root/.//node_modules/@sls-next/aws-cloudfront/node_modules/aws-sdk/lib/request.js:38:9)
                                  at Request.<anonymous> (/root/.//node_modules/@sls-next/aws-cloudfront/node_modules/aws-sdk/lib/request.js:688:12)
                                  at Request.callListeners (/root/.//node_modules/@sls-next/aws-cloudfront/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
                                  at Request.emit (/root/.//node_modules/@sls-next/aws-cloudfront/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
                                  at Request.emit (/root/.//node_modules/@sls-next/aws-cloudfront/node_modules/aws-sdk/lib/request.js:686:14)
                                  at Request.transition (/root/.//node_modules/@sls-next/aws-cloudfront/node_modules/aws-sdk/lib/request.js:22:10)
                                  at AcceptorStateMachine.runTo (/root/.//node_modules/@sls-next/aws-cloudfront/node_modules/aws-sdk/lib/state_machine.js:14:12)
                                  at /root/.//node_modules/@sls-next/aws-cloudfront/node_modules/aws-sdk/lib/state_machine.js:26:10
                                  at Request.<anonymous> (/root/.//node_modules/@sls-next/aws-cloudfront/node_modules/aws-sdk/lib/request.js:38:9)
                                  at Request.<anonymous> (/root/.//node_modules/@sls-next/aws-cloudfront/node_modules/aws-sdk/lib/request.js:688:12)
                                  at Request.callListeners (/root/.//node_modules/@sls-next/aws-cloudfront/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
                                  at callNextListener (/root/.//node_modules/@sls-next/aws-cloudfront/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
                                  at IncomingMessage.onEnd (/root/.//node_modules/@sls-next/aws-cloudfront/node_modules/aws-sdk/lib/event_listeners.js:335:13)
                                  at IncomingMessage.emit (events.js:412:35)
                                  at IncomingMessage.emit (domain.js:475:12)
                                  at endReadableNT (internal/streams/readable.js:1334:12)
                                  at processTicksAndRejections (internal/process/task_queues.js:82:21) {
                                  code: 'TooManyDistributionsWithLambdaAssociations',
                                  time: 2022-04-08T20:29:11.771Z,
                                  requestId: '11a88645-b04f-4da8-ba7b-e4f3f4a54001',
                                  statusCode: 400,
                                  retryable: false,
                                  retryDelay: 177.49810944895628
                                  }
2022-04-08T20:29:11.812Z [ERROR]: TooManyDistributionsWithLambdaAssociations
Terminating logging...
```

@hloriana If we cannot be given more explicit mitigation steps and/or proper fix timelines from AWS on this, I will have to advise the company to abandon AWS Amplify for Next.js apps and migrate to a competing service such as Vercel or Netlify.

**Comment by vandreleal** [comment]
Hi @Alek-S , I understand that the following suggestion require manual action, which is not ideal, but I thought it would be worth mentioning in case they help you and your team. You can remove disabled distributions from the CloudFront panel to remove lambda associations that are counted in the total of associations even though they are not in use. Another suggestion would be going to the `Rewrites and redirects` section on Amplify to identify the existence of multiple active distributions that may no longer be needed as the distribution at the top is usually the one in use.

**Comment by vandreleal** [comment]
I understand @Alek-S , it's indeed time-consuming and a manual process that becomes a burden to the team. As you said, preview builds are particularly troublesome to review even though resources are usually created under a common pattern `\d{6-7}-\d{6,7}`. Our number of active buckets, lambda functions, IAM roles, and CF distributions started spiking around the time @arbass22 posted a new comment 13 days ago, which I believe may also be the case for you. It seems to happen intermittently as it was not happening before, though.

**Comment by hloriana** [comment]
Hello everyone, apologies for the delay in update. The engineers have been working on a fix for this issue and it will be rolled out soon but I do not have an exact date for when the rollout will be complete. We will provide another update when the bug fix has been deployed.

**Comment by ctopherwilliams** [comment]
Any updated ETA here?

**Comment by kahdojay** [comment]
Ok, closing this one for now, but please re-open and provide details if you're still running into this issue!

**Comment by imdkbj** [comment]
This is still happening... Pls check...

_Action is showing as in-progress on github but actually deleted from the amplify_


<img width="867" alt="image" src="https://user-images.githubusercontent.com/46839821/178218561-f56e5fbd-9d0b-4066-98ec-4970d83fd5fe.png">

No effect if timeout
<img width="398" alt="image" src="https://user-images.githubusercontent.com/46839821/178218680-54a6d811-b969-4c83-8359-789cc8aeb4ff.png">


Actually not found any in-progress pr build on amplify console but this keeps running at github.

<img width="1124" alt="image" src="https://user-images.githubusercontent.com/46839821/178219008-24937c20-6bb9-4518-ab63-f19a463014fb.png">
