### ISSUE TITLE
miss cloud front on browser 

### ISSUE THREAD

**Issue by hokidoki** [aws-amplify/amplify-hosting#2563]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d2joh8jz57nkvq

### Region

ap-northeast-2

### Amplify Console feature

Performance

### Describe the bug

Hello . 

I installed Next.js following the AWS guide and hosted it on amplify. 

However, every time I made a request to my service, the response was so slow. So, looking at the response header, the x-cache: Miss from cloudfront header is always present on browser. So I followed the instructions and enabled performance mode on my brunch in amplify but I'm still having the same problem. 

The curious thing is that if you look at the x-cache header with the curl command, it was hit. 

`curl -X HEAD -i https://v.place.hitit.xyz/store/80e0a902-490f-4d96-b18d-988c852b2975 -s | grep -Fi x-cache
x-cache: Hit from cloudfront
`

I suspect this is region related. Could you please check this as well ?

lambdaEdge : us-east-1
lambda : us-east-1
s3 : us-east-1
amplify : ap-northeast-2

### Expected behavior

I don't have any customHttp.yml . it was problem ? 

### Reproduction steps

just enter my website.

https://v.place.hitit.xyz/
https://v.place.hitit.xyz/store/80e0a902-490f-4d96-b18d-988c852b2975

**Comment by Narrator** [comment]
Hello, this is a known issue and we are working on a permanent fix.

As a workaround, please disable caching in your SSR distribution (Go to **Behaviors** in the CloudFront console and set min/max TTL to 0 for all behaviors). This should resolve the issue until we have a permanent fix in place.

**Comment by hokidoki** [comment]
@Narrator hello Narrator 

it work .but It's not a good idea to manually set the TTL every time I deploy.

When I asked the support team, they said that TTL is set by default and there is no way I can change it before deployment. Does any way exist?

**Comment by beam36** [comment]
@Narrator I tried the workaround you suggested but doesn't seem to work for me
My app id is d3aaj2ksbpdnai, region ap-southeast-1
We use this script to test
```
while true; do curl -X HEAD -i https://truck.isuzu-tis.com/product/gxz -s | grep -Fi x-cache; sleep 2; done
x-cache: Miss from cloudfront
```

**Comment by beam36** [comment]
After turned on the performance mode, the script does return 'Hit' but when I look at the network tab in Chrome, I still see 'Miss'

**Comment by beam36** [comment]
@saadataz I don't disable cache. Screenshot attached
<img width="1368" alt="Screen Shot 2022-02-19 at 5 37 16 PM" src="https://user-images.githubusercontent.com/13551560/154797381-687a2157-186a-4423-aed1-13055e610bc1.png">

**Comment by saadataz** [comment]
Thank you for confirming @beam36. We are actively working on fixing the issue.

**Comment by beam36** [comment]
@saadataz  So there is no workaround?

**Comment by beam36** [comment]
@Narrator @saadataz It's been almost 2 months. Is there any update? If there's no fix soon, we'll have to consider moving to another platform.

**Comment by saadataz** [comment]
@beam36 This is still work in progress. We will update this thread as soon as the issue fixed.

**Comment by beam36** [comment]
@saadataz Is this something you guys are still actively working on? No update at all?

**Comment by oliver-leung** [comment]
We have deprioritized the fix for this issue, since it will be resolved when we release the next iteration of our SSR service.

**Comment by sarunxko** [comment]
@oliver-leung Can you confirm if there's any workaround and when you says next iterations are you talking weeks, months or year?

**Comment by beam36** [comment]
@oliver-leung Can you confirm if there's any workaround (the one mentioned above doesn't work for me)? And can you say if the next iteration is weeks, months, or years?

**Comment by oliver-leung** [comment]
Unfortunately, we don't have a workaround, nor an estimated date by which it will be resolved.

**Comment by 70ki8suda** [comment]
still not fixed ? I face same issue.

**Comment by oliver-leung** [comment]
@beam36 @70ki8suda @hokidoki We've since released our next iteration of our SSR provider - please follow the steps here to migrate your app: https://docs.aws.amazon.com/amplify/latest/userguide/update-app-nextjs-version.html

If you're still facing this issue, please reopen this issue and we'll take another look!

**Comment by 70ki8suda** [comment]
@oliver-leung 
Hi, I migrated my app(using Nextjs ver13) to web computing platform.
When using performance mode, instant cache invalidation on deployment does not work and a cache from a previous deployment remains in Cloud Front and references an old non-existent static file, resulting in a bug that does not display properly.
This does not happen in every browser. But if one browser picked up old CDN cache, it remains showing inappropriate display until CDN cache expires.

**Comment by MVMS1994** [comment]
Hi team, we are also facing this issue. We have hosted our webpack built web application. The assets are always miss from cloudfront and the downloads are delayed because of that. Can you share some ETA on this fix?

**Comment by anatolzak** [comment]
I am having the same issue with a simple next.js ssr, ssg apps, gatsby apps. All requests come back with `X-Cahce: Miss from cloudfront`

This issue was opened more than 1.5 years ago. I would expect a solution by now

**Comment by kkak10** [comment]
I'm having the same problem. In the React CSR App environment, the requesting Asset is not doing Cache Hit. Because of this, there is a problem with the initial loading speed.

**Comment by anatolzak** [comment]
Are there any plans on fixing this issue? 
We will be forced to move away from AWS Amplify to a service that actually works

**Comment by adidoes** [comment]
is this still an issue?

**Comment by anatolzak** [comment]
@adidoes yes, it's still an issue

**Comment by teamzz111** [comment]
+1

**Comment by airton** [comment]
+1

**Comment by cercao** [comment]
+1

**Comment by Timfts** [comment]
+1

**Comment by EsteBustamante** [comment]
@rubengommers, good catch! I was able to observe the behavior you suggested the `x-cache: Hit from CloudFront` is returned when I manually flush the cookies and refresh the page. However, increasing the TTL through the cache-control headers didn't resolve the issue. I suppose we'll have to wait for AWS to provide input here, but being close to 2 years, i don't feel optimistic

**Comment by oshyn-inc** [comment]
I believe this would work if we could override the Cloudfront policy for Amplify so we could modify the Cookie settings in the Cache key.  It is very common for cookies to update their TTL every request.  This behavior is causing the default Managed-Amplify policy (which uses Cookies - All Cache Key Setting) to think the request is a brand new cache entry (causing way more cache usage than necessary).  If we could attach our own custom policy we could change that Cookie setting by excepting Cookies or including only ones whose Expiration Date does not change every request.  Without this, amplify does not cache and the utility of the entire service is in doubt.

**Comment by EsteBustamante** [comment]
@Narrator @oliver-leung any thoughts?

**Comment by 6mdx** [comment]
Very frustrating for nearly two years and the issue has not been fixed 😔

**Comment by wujashek** [comment]
+1

**Comment by canuysal** [comment]
+1

**Comment by EleazerToluan** [comment]
+1

**Comment by ShwareAPI** [comment]
+1

**Comment by mauops** [comment]
+1

**Comment by hasadata** [comment]
+1

**Comment by guy-a** [comment]
+1

**Comment by gvsakhil** [comment]
Its been more than 2 years and still the issue is not fixed.... So baddddd AWS.....

**Comment by wujashek** [comment]
Just wanted to say "Hi" from Vercel :)

**Comment by mauerbac** [comment]
Hey everyone - Matt from the Amplify team here. First, I want to apologize for the delay in communication. The GitHub issue has a few themes - cache hit ratio, Instant cache invalidation and cookies in cache key. Cache hit ratio improvements and the ability to remove cookie from the cache key we are activity working on. This will greatly help the cache hit ratio and from this issue seems to be root of the most pain around cache. Instant cache invalidation has been addressed and is supported today. 

We are hoping to have the ability to remove cookies from the cache key in the next couple of months. I will update this issue when that is released. Thank you for your patience.

**Comment by benebrice** [comment]
I have the exact same behavior described previously. For now, the only solution I found is to load the page from a private navigation (working on Safari). If version is not up to date, I close the window and try again. 🤦🏻 

@mauerbac do you have any news for us? It's been a really long time since the opening of this issue.

**Comment by evokelabs** [comment]
I'm experiencing this same issue from two years ago. Using AWS amplify to build a git repository results in all public assets having a max-age of 5 seconds in cache-control. The files in the public folder don't cache on CloudFront, and will always return as a miss when it ought to be a hit via X-Cache. This leads to poor and costly performance as public assets are fetched from the origin every time to rebuild the cache, only to be removed 5 seconds later. 

None of the fixes listed in this thread or others work (creating custom header ruleset in the build, or in customHttp.yml, or setting it to performance mode) - so max-age is always 5.  I've tested the same build (Next 12 SSR) on Vercel and Netlify and they all cache the files in the public folder using CloudFront just fine out of the box, with the max-age being increased to hours/days by default.  Right now I've to circumvent this issue by creating a S3 bucket, storing the public asset files in there, use another CloudFront instance to distribute that S3, and then update the URL in the Next application to use that CloudFront URL so caching will work.

**Comment by kevcube** [comment]
This is still a problem 2 years later. @mauerbac @oliver-leung can you please reassess the priority of this issue? We were previously serving our frontend from a fargate container running behind an ALB with no CDN and it was globally accessible faster than our deployment now through cloudfront with amplify performance mode enabled. Shockingly disappointing, especially considering the age of this issue :(

time-to-first-byte is 6.5 seconds 😭

**Comment by Gowiem** [comment]
I hate chiming in on known issues that are not getting addressed, but... going to do it on this one due to how bad this is: 

1. It's been stated before, but this is insane to see still open. We're rolling out Amplify to a client organization right now and as the tech lead who pushed to bring in Amplify... finding this issue late in the game is highly demoralizing in our usage of this service. In our own use-case and from reading the above, there is basically no benefit to having the CDN in front of the static assets at all. You can get a cache hit on first page load, but from then on you only get cache misses? It's like some sort of twisted joke of a bug because that is exactly the opposite functionality that you want from a CDN. I expect (and typically see) a lot better from AWS in regards to issues like this. Particularly ones that are so old. This is the type of thing I expect to see from Azure, not AWS. 

2. For all 30+ participants who have weighed in or commented on this, please be sure to 👍 the root issue. I'm surprised to see 30+ people involved in this thread and yet less than 10 "👍" on this one. OSS projects typically sort their issues by 👍 , so that may be one way to get this issue higher up on the priority list for @mauerbac + team.

**Comment by cburne-oshyn** [comment]
I just thumbs up'd it.  However, we solved this issue by just rolling our own set of services Lambda, Cloudfront, CDN, Redis, API Gateway.  It wasn't too challenging.  My colleague did it recently and has in his queue to do a blog post on it.

**Comment by mauerbac** [comment]
Hi everyone -- apologize again for the delayed response. I totally understand the pain and performance issues that can be caused around how static assets are cached, etc... The team has been working on this as a high priority item since my last comment and we will have a big update next Tuesday on this. To give you an idea of the changes- static assets will automatically have a longer ttl apart of the cache policy, ability to strip cookies from the cache key, forwarding all CloudFront headers and i18n Next.js support. I'm confident you will see significant caching improvements with these changes. I will share the blog post on this next week. 

@Gowiem also happy to hop on a call and walk you through the changes

**Comment by Gowiem** [comment]
@mauerbac really appreciate your response here and I'm relieved to hear the fix is on the very short-term horizon! Thank you for getting back and pushing this forward, we're eager to kick the tires as soon as it is live! 💯

**Comment by mropanen-vincit** [comment]
Any updates yet?

**Comment by mauerbac** [comment]
Hey all- following-up from my previous update. I'm excited to say that we are now looking to provide early access to these enhancements to a few customers from this thread!

We have provided the following: a mechanism to strip cookies from the cache key, made it so static assets will automatically have a longer ttl apart of the cache policy, started forwarding all CloudFront headers and enable i18n Next.js support via the Accept-Language header. We are seeing large performance gains here from our internal testing. 

If you would like to have the above benefits allow-listed in your account, please email me your accountID to mauerbac@amazon.com

**Comment by mauerbac** [comment]
@Gowiem @mropanen-vincit , would love to get both of you in early access. Please LMK!

**Comment by Gowiem** [comment]
@mauerbac awesome -- I'll reach out via email. Thanks for the follow up 💯

**Comment by hasadata** [comment]
@mauerbac I sent you my accountID

**Comment by sjpriest** [comment]
I've been tracking this issue closely on this thread: https://github.com/aws-amplify/amplify-hosting/issues/2243#issuecomment-2187241489

I'll be very pleased to have a simple fix for the issue, whether it's now or after a short period of time. @mauerbac I'll send you an email shortly.

**Comment by carvantes** [comment]
Hi, today we launched caching improvements for Amplify that address this issue. Check out the details here:
- https://aws.amazon.com/blogs/mobile/cdn-caching-improvements-for-better-app-performance-with-aws-amplify-hosting/
- https://docs.aws.amazon.com/amplify/latest/userguide/caching.html
