### ISSUE TITLE
App not showing Build Status

### ISSUE THREAD

**Issue by SantoshRaoMea** [aws-amplify/amplify-hosting#3067]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d3ul78bzrlc05b

### AWS Region

eu-west-2

### Amplify Hosting feature

Backend builds, Build settings, Frontend builds

### Describe the bug

All my apps in eu-west show a build status on main amplify console list app page like Running, Pending etc

However app with id d3ul78bzrlc05b, doesnt show this on list page, i can go to the app inside and check build status.

### Expected behavior

Amplify List Page should show build status for every app

### Reproduction steps

Dont have steps to reproduce, it is just that one of the many apps that i have created in same manner, is experiencing this issue in the UI

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by hloriana** [comment]
Hi @SantoshRaoMea 👋🏽 can you provide a screenshot of the missing build step? I just deployed an app in the same region and I'm unable to reproduce this behavior in the UI.

**Comment by SantoshRaoMea** [comment]
<img width="1420" alt="image" src="https://user-images.githubusercontent.com/91133698/199171697-cb1ecd02-0745-4876-8636-9da372802620.png">

The Build works well, but on the Apps Page if you see it doesnt show the Status in Green for the 1st App 
meaplatform-mosaic-preprod

**Comment by SantoshRaoMea** [comment]
@hloriana  Did you get a chance to look at this please?

**Comment by SantoshRaoMea** [comment]
@calavera , thanks for getting back. Below is the new screenshot, yes the UI has changed, but still the problem persists please observe the top right card meaplatform-mosaic-preprod, there is no build status and time since build being shown.

<img width="1454" alt="image" src="https://user-images.githubusercontent.com/91133698/203453324-80bdeb85-39a3-4d61-82ef-f5324a206c90.png">

**Comment by SantoshRaoMea** [comment]
Any update on this @hloriana

**Comment by nadetastic** [comment]
related #3497

**Comment by Jay2113** [comment]
Hi @SantoshRaoMea 👋 , thanks for your continued patience and apologies for the delayed response on the thread.

Your Amplify app `meaplatform-mosaic-preprod` has a branch named `mosaic-preprod` and it currently does not have a `stage` associated to it: https://docs.aws.amazon.com/amplify/latest/APIReference/API_AutoBranchCreationConfig.html#amplify-Type-AutoBranchCreationConfig-stage

To list the apps in the Amplify Console UI, we use the [ListApps API](https://docs.aws.amazon.com/amplify/latest/APIReference/API_ListApps.html) and it uses the `status` attribute of the production branch to display the build status and last deploy time: https://docs.aws.amazon.com/amplify/latest/APIReference/API_ProductionBranch.html#amplify-Type-ProductionBranch-status

To associate a stage to your app's branch, you will need to complete the following steps:
- Navigate to the Amplify Console and select the Amplify app
- Under `App settings` navigate to `General`
- Click the `Edit` button which is located on the top right corner of the console
- Under the `Repository settings` section, navigate to the `Production environment` field
- From the `Production environment` field dropdown, select the branch name 
- Click the `Save` button
- Navigate to the `All Apps` view in the Amplify Console

Your Amplify app should now display the build status and the last deploy time.

**Comment by SantoshRaoMea** [comment]
@Jay2113 : Thanks for the steps, it is showing perfectly now, thanks for the same
