### ISSUE TITLE
Cold start taking 10-12 seconds to render static page

### ISSUE THREAD

**Issue by rkingonnw** [aws-amplify/amplify-hosting#3211]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d15y9mlar87m44

### AWS Region

us-east-1

### Amplify Hosting feature

Not Applicable

### Describe the bug

Upon new deployment and/or after the app goes idle, we are experiencing a 10-12 second delay on any page of our Next13 application. We are on the new Web Compute platform.

Mere speculation wants to blame Lambda Cold Start -- but I am not 100% sure if that is the case -- either way, a public facing UI should never be faced with a 10-12 second cold start.

### Expected behavior

Loads in reasonable time

### Reproduction steps

1. Fresh deploy and visit the site
2. Let sit idle for a period of time and visit the site

### Additional information

We have a sample build up [here](https://pr-43.d15y9mlar87m44.amplifyapp.com/amplify-test)

Screenshot shows a 10 second request
![Screenshot 2022-12-21 at 11 17 15 AM](https://user-images.githubusercontent.com/109250371/208981989-e971313f-4eff-44f1-8dc1-9a2f6093753a.png)

**Comment by rkingonnw** [comment]
this looks to be identical to: https://github.com/aws-amplify/amplify-hosting/issues/2647

it was closed as part of launching support for Next 12/13 -- but the behavior still exists

**Comment by rkingonnw** [comment]
bump

**Comment by LucasLemanowicz** [comment]
Related to high TTFB issue here: https://github.com/aws-amplify/amplify-hosting/issues/3122 which is tagged as "investigating" (but no new update in nearly a month)

**Comment by yuyokk** [comment]
I was about to submit the bug as well but came across this one.

We are getting time_starttransfer ~14 / 13 seconds on latest Nextjs project (measured like this https://stackoverflow.com/questions/18215389/how-do-i-measure-request-and-response-times-at-once-using-curl) e.g.

```bash
time_namelookup:     0.152133
time_connect:        0.168539
time_appconnect:     0.210377
time_pretransfer:    0.210509
time_redirect:       0.000000
time_starttransfer:  14.235495
----------
time_total:          14.236349
```

14 seconds is way too much :(

Amplify app id = _d3jjevefis395x_
Region = _us-east-1_

**Comment by stefanzier** [comment]
I also have a Next13 app and enabling "[performance mode](https://docs.aws.amazon.com/amplify/latest/userguide/ttl.html#Performance-mode)" seemed to do nothing for me as TTFB was still quite bad (~5-10s). Upon inspection of the headers, I noticed the cache would always report `Miss from CloudFront` and I could not see `s-maxage` set.

Not sure if this will work for you but setting the header explicitly in `next.config.js` seemed to have worked for me and now my site loads much much faster. Would be great if someone from Amplify team can confirm this is a valid workaround.

```
...
const nextConfig = {
    ...
    headers: async () => {
        return [
            {
                source: '/(.*)',
                headers: [
                    {
                        key: 'Cache-Control',
                        value: 'public, s-maxage=86400'
                    }
                ]
            }
        ];
    }
};
...
```

**Comment by hloriana** [comment]
Hi @mr-rpl @stefanzier @yuyokk 👋🏽 apologies for the delay here. Are you leveraging BugSnag in your `package.json`?  We have seen instances where packages like BugSnag have contributed ~12 seconds to the app initialization time which accounts for the high TTFB. 

We are continuing to investigate which other dependencies can also have this affect on TTFB and will update this issue accordingly.

**Comment by yuyokk** [comment]
@hloriana we dont use BugSnag for our project.

**Comment by jdpst** [comment]
@hloriana Same issue on our project. We do not use BugSnag. Here are the dependencies we use (I've omitted a few internal config packages):

```
  "dependencies": {
    "@apollo/client": "^3.7.5",
    "@emotion/react": "^11.10.5",
    "@emotion/server": "^11.10.0",
    "@emotion/styled": "^11.10.5",
    "@mui/icons-material": "^5.11.0",
    "@mui/lab": "^5.0.0-alpha.117",
    "@mui/material": "^5.11.6",
    "@mui/x-data-grid": "^5.17.20",
    "@mui/x-date-pickers": "^5.0.15",
    "@react-pdf/renderer": "^3.0.2",
    "@sentry/integrations": "^7.33.0",
    "@sentry/nextjs": "^7.33.0",
    "@sentry/replay": "^7.33.0",
    "@sentry/tracing": "^7.33.0",
    "@turf/helpers": "^6.5.0",
    "async-retry": "^1.3.3",
    "aws-amplify": "^5.0.11",
    "cheerio": "^1.0.0-rc.5",
    "country-code-lookup": "^0.0.22",
    "docx": "^7.8.2",
    "file-saver": "^2.0.5",
    "flat": "^5.0.2",
    "graphql": "^16.6.0",
    "heic2any": "^0.0.3",
    "jszip": "^3.10.1",
    "lodash": "^4.17.21",
    "luxon": "^3.2.1",
    "mapbox-gl": "^2.12.0",
    "next": "^13.1.5",
    "pdfjs-dist": "^2.16.105",
    "prop-types": "^15.8.1",
    "react": "^18.2.0",
    "react-csv": "^2.2.2",
    "react-dom": "^18.2.0",
    "react-google-button": "^0.7.2",
    "use-debounce": "^8.0.4",
    "yup": "^0.32.11"
  },
  "devDependencies": {
    "@graphql-codegen/cli": "^2.16.4",
    "@graphql-codegen/introspection": "^2.2.3",
    "@graphql-codegen/near-operation-file-preset": "^2.5.0",
    "@graphql-codegen/typescript": "^2.8.7",
    "@graphql-codegen/typescript-apollo-client-helpers": "^2.2.6",
    "@graphql-codegen/typescript-operations": "^2.5.12",
    "@types/async-retry": "^1.4.5",
    "@types/cheerio": "^0.22.31",
    "@types/file-saver": "^2.0.5",
    "@types/flat": "^5.0.2",
    "@types/google-map-react": "^2.1.7",
    "@types/luxon": "^3.2.0",
    "@types/mapbox-gl": "^2.7.10",
    "@types/react": "^18.0.27",
    "@types/react-csv": "^1.1.3",
    "@types/react-dom": "^18.0.10",
    "eslint": "^8.32.0",
    "get-graphql-schema": "^2.1.2",
    "standard-version": "^9.5.0",
    "typescript": "^4.9.4",
    "unimported": "^1.24.0"
```

**Comment by stefanzier** [comment]
@hloriana same, no bugsnag. I have a very simple nextjs application. Unfortunately, I was tired of +10min build times and these cache issues, so I just moved to Vercel but kept Amplify as my backend. Now things are great but I hope to use Amplify hosting in the future if these issues are addressed 🙏

**Comment by mr-rpl** [comment]
> 



> Hi @mr-rpl @stefanzier @yuyokk 👋🏽 apologies for the delay here. Are you leveraging BugSnag in your `package.json`? We have seen instances where packages like BugSnag have contributed ~12 seconds to the app initialization time which accounts for the high TTFB.
> 
> We are continuing to investigate which other dependencies can also have this affect on TTFB and will update this issue accordingly.

@hloriana we are not, our dep tree is:
```
  "dependencies": {
    "@apollo/client": "^3.7.0",
    "@datadog/browser-rum": "^4.21.2",
    "@emotion/react": "^11.10.0",
    "@emotion/styled": "^11.10.0",
    "@mui/icons-material": "^5.10.9",
    "@mui/lab": "^5.0.0-alpha.95",
    "@mui/material": "^5.10.1",
    "@optimizely/react-sdk": "^2.9.1",
    "formik": "^2.2.9",
    "graphql": "^16.6.0",
    "next": "^13.0.7",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "use-is-in-viewport": "^1.0.9",
    "uuid": "^9.0.0"
  },
```

fwiw, we are now running on Vercel and have no issues

**Comment by yuyokk** [comment]
@hloriana not sure if it helps but we use [`mui`](https://mui.com/) in our deps as well (common package with @mr-rpl and @jdpst)

**Comment by jdpst** [comment]
@yuyokk @mr-rpl @hloriana I have set up a CloudWatch synthetic canary to ping the relevant URL every few mins, which seems to be _good enough_ since most requests take <10ms so it's rare that we need >1 hot lambda. Far from perfect, but sufficient as a workaround until this issue can be resolved.

**Comment by mr-rpl** [comment]
I wanted to pull the MUI thread -- I deployed a fresh shell next13 app to amplify and still experienced the 10-12second load. Zero additional dependencies.

@jdpst - i seem to get the lag even without waiting from time to time -- and especially after a deploy (first load) -- so for that, i personally wouldn't put anything into production

**Comment by mr-rpl** [comment]
another finding whilst triaging: I found that this only happens when using the `pages` directory. if using the new nextjs13 `app` dir, the 10-12second hang time goes away.

of course, it brought up a new bug: revalidate seems to happen at exactly 3 minutes no matter what I set the param to 😂

**Comment by yuyokk** [comment]
We setup Cloudwatch Heartbeat Monitor to ping page every minute. We dont see 14s for time to first byte anymore, but still see ~4s occasionally.

<img width="2081" alt="Screen Shot 2023-02-01 at 10 15 54 AM" src="https://user-images.githubusercontent.com/1225343/216001617-36022cf5-f737-4b0f-aa3f-03282aafc890.png">

I wish we could just migrate to Vercel but unfortunately we are tied to AWS here :(

**Comment by mstoyanovv** [comment]
> another finding whilst triaging: I found that this only happens when using the `pages` directory. if using the new nextjs13 `app` dir, the 10-12second hang time goes away.
> 
> of course, it brought up a new bug: revalidate seems to happen at exactly 3 minutes no matter what I set the param to 😂

I switched from 'pages' to 'app' directory and there is still 3 seconds TTFB which is unacceptable for a production application. The same app deployed to vercel is getting under 100 ms TTFB ...

**Comment by rapgodnpm** [comment]
I get between 6 - 14 seconds TTFB. I use MUI. Is there any update on this? I've switched to netlify but would love to use amplify instead.

**Comment by talaikis** [comment]
People, if you're paying for Amplify hosting, why not enable Route 53 health check? That $1 solves the problem.

**Comment by rapgodnpm** [comment]
> People, if you're paying for Amplify hosting, why not enable Route 53 health check? That $1 solves the problem.

Did you actually try? I’ve made a lambda that calls my website every 9 minutes and it didn’t seem to solve anything

**Comment by talaikis** [comment]
> Did you actually try? I’ve made a lambda that calls my website every 9 minutes and it didn’t seem to solve anything

Sure, working since I've subscribed here, month+ on one site and another does not even require it. Both have service workers though, checking on clean uncached browser.

**Comment by rapgodnpm** [comment]
> > Did you actually try? I’ve made a lambda that calls my website every 9 minutes and it didn’t seem to solve anything
> 
> Sure, working since I've subscribed here, month+ on one site and another does not even require it. Both have service workers though, checking on clean uncached browser.

Hmm, thank you for your suggestion, I will try

**Comment by mstoyanovv** [comment]
> People, if you're paying for Amplify hosting, why not enable Route 53 health check? That $1 solves the problem.

I am not exactly sure what do you mean but enabling health checks with frequency of 30 seconds does not fix the issue for me. There is still 4-5 seconds of TTFB..

**Comment by talaikis** [comment]
> I am not exactly sure what do you mean but enabling health checks with frequency of 30 seconds does not fix the issue for me. There is still 4-5 seconds of TTFB..

How the same site works outside of the Amplify?

**Comment by mstoyanovv** [comment]
> > I am not exactly sure what do you mean but enabling health checks with frequency of 30 seconds does not fix the issue for me. There is still 4-5 seconds of TTFB..
> 
> How the same site works outside of the Amplify?

Works perfectly fine in vercel without any changes to the site.

**Comment by sig003** [comment]
I found a case that I can solve. I used a next.js and amplify hosting.
Redirect to another page when accessing the index of my service.

`
ex)
https://example.com/ 

=> redirect

https://example.com/foo
`

At this time, TTFB takes more than 3 seconds.
But it is fast when approaching directly.

`
ex)

https://example.com/foo
`

Before that, do the following settings.

`
1) Enable amplify's performance mode.
2) Setting amplify's custom header.

customHeaders:
  - pattern: '**/*'
    headers:
      - key: Cache-Control
        value: 'max-age=86400, s-maxage=86400'
`

Maybe there's a problem between Amplify and the redirect of next.js?

**Comment by talaikis** [comment]
I've experienced problems with *some* of the redirects when using Next 13. Downgrading to Next 12 solved the problem for me. And that was not just 3-13 seconds, but full browser freeze. Wasn't able to reproduce on a smaller app.

**Comment by IvanCaceres** [comment]
Getting extremely high TTFB ~15 second response time for SSR routes in our Next.js 13 amplify hosting compute app

**Comment by abenzick** [comment]
This thread details my exact problems. Trying to launch a site with nextJS + Amplify but this cold start issue >10 seconds is a show stopper.

**Comment by OxBlossom** [comment]
- I am not even on Next13
- Neither using BugSnag
- Opening my website for the first time on any Browser/Device is taking 15 seconds... it should have been 100ms 
- Even applied settings
`
cache:
  paths:
    - 'node_modules/**/*' # Cache `node_modules` for faster `yarn` or `npm i`
    - '.next/cache/**/*'
`

But this doesn't seem to solve this issue. 
Yes After it is loaded for the first time, the next time I instantly get it. 

15 second cold start for a small web app is unacceptable.

my dependencies:

`
{
  "dependencies": {
    "@emotion/react": "^11.4.1",
    "@emotion/styled": "^11.3.0",
    "@mui/icons-material": "^5.0.3",
    "@mui/material": "^5.0.3",
    "@mui/system": "^5.11.1",
    "@mui/x-date-pickers": "^5.0.0-alpha.7",
    "@sentry/nextjs": "^7.25.0",
    "@stripe/react-stripe-js": "^1.4.1",
    "@stripe/stripe-js": "^1.15.1",
    "@twilio/conversations": "^2.0.0",
    "@twilio/video-processors": "^1.0.2",
    "@typeform/embed": "^1.6.1",
    "axios": "^0.21.1",
    "chart.js": "^3.7.0",
    "core-js": "^3.9.1",
    "date-fns": "^2.29.3",
    "emoji-mart-next": "^2.11.2",
    "form-data": "^4.0.0",
    "jest-canvas-mock": "^2.4.0",
    "jsonwebtoken": "^9.0.0",
    "lottie-web": "^5.9.2",
    "material-ui-phone-number": "^3.0.0",
    "md5": "^2.3.0",
    "moment": "^2.29.1",
    "moment-timezone": "^0.5.34",
    "next": "12.3.4",
    "next-redux-wrapper": "^6.0.2",
    "nylas": "^6.4.2",
    "query-string": "^7.0.0",
    "rc-time-picker": "^3.7.3",
    "react": "^18.2.0",
    "react-calendar": "^3.3.1",
    "react-chartjs-2": "^4.0.1",
    "react-countup": "^6.0.0",
    "react-csv-reader": "^3.5.0",
    "react-data-table-component": "^7.0.0-alpha-5",
    "react-dom": "^18.2.0",
    "react-draggable": "^4.4.4",
    "react-google-login": "^5.2.2",
    "react-image-crop": "^10.0.4",
    "react-infinite-scroll-component": "^6.0.0",
    "react-linkedin-login-oauth2": "^1.0.9",
    "react-material-ui-form-validator": "^3.0.1",
    "react-modal": "^3.13.1",
    "react-phone-number-input": "^3.1.47",
    "react-quill": "^1.3.5",
    "react-redux": "^7.2.3",
    "react-responsive-carousel": "^3.2.16",
    "react-slick": "^0.28.1",
    "react-thunk": "^1.0.0",
    "react-time-picker": "^4.2.1",
    "react-visibility-sensor": "^5.1.1",
    "redux": "^4.0.5",
    "redux-thunk": "^2.3.0",
    "request": "^2.88.2",
    "slick-carousel": "^1.8.1",
    "stripe": "^8.157.0",
    "styled-components": "^5.2.1",
    "tslib": "2.5.0",
    "twilio": "^3.71.1",
    "twilio-video": "^2.18.1",
    "universal-emoji-parser": "^0.5.28",
    "winston-papertrail-transport": "^1.0.9",
    "wow.js": "^1.2.2"
  },
  "devDependencies": {
    "@testing-library/jest-dom": "^5.14.1",
    "@testing-library/react": "11.2.5",
    "@types/cron": "^2.0.0",
    "@types/express": "4.17.11",
    "@types/jest": "^27.0.1",
    "@types/node": "16.11.7",
    "@types/react": "17.0.3",
    "@types/react-dom": "17.0.3",
    "@types/react-material-ui-form-validator": "^2.1.1",
    "@types/react-modal": "^3.12.0",
    "@types/react-slick": "^0.23.4",
    "@types/supertest": "^2.0.12",
    "@typescript-eslint/eslint-plugin": "^5.46.1",
    "@typescript-eslint/parser": "^5.46.1",
    "babel-jest": "26.6.3",
    "cypress": "^6.8.0",
    "eslint": "^8.2.0",
    "eslint-config-airbnb": "19.0.4",
    "eslint-config-airbnb-typescript": "^17.0.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-import-resolver-typescript": "^3.5.2",
    "eslint-plugin-import": "^2.26.0",
    "eslint-plugin-jest": "^27.1.7",
    "eslint-plugin-jsx-a11y": "^6.5.1",
    "eslint-plugin-prettier": "^4.2.1",
    "eslint-plugin-react": "^7.28.0",
    "eslint-plugin-react-hooks": "^4.3.0",
    "husky": "^8.0.2",
    "jest": "26.6.3",
    "jest-canvas-mock": "^2.4.0",
    "lint-staged": "^13.0.2",
    "node-sass": "^8.0.0",
    "prettier": "^2.8.1",
    "supertest": "^6.2.3",
    "ts-jest": "26.5.4",
    "ts-node": "~9.1.1",
    "tslint": "~6.1.3",
    "typescript": "^4.3.2"
  },
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged && echo '!! Husky is DONE Reviewing !!'"
    }
  },
  "lint-staged": {
    "*.{scss,css,md}": "prettier --write",
    "*.{ts,tsx}": [
      "yarn format",
      "yarn lint"
    ]
  }
}

`

**Comment by OxBlossom** [comment]
<img width="518" alt="Screenshot 2023-02-16 at 2 10 33 PM" src="https://user-images.githubusercontent.com/119491300/219319829-b43c8025-d5b5-45e0-b981-74e532c801e9.png">

as mentioned by @yuyokk my time_starttransfer is under 1 sec, which is fine.
but cold start sucks big!

**Comment by JianWang2016** [comment]
@mstoyanovv, when you use next 13 app folder, where do you specify Amplify.configure({ ...config, ssr: true })? I put it in layout.jsx but my app seems to have a hard time to find it.  It from time to time complains about no credentials.  I also tried Amplify.configure({ ...config}) without much success.  No documentation on about this.  Any insight would be greatly appreciated.

**Comment by OxBlossom** [comment]
@rapgodnpm I observed in the build settings that you can `enable performance mode` for specific branch..
It gives a Docker image on a host with 4 vCPU, 7GB memory.

**Comment by rapgodnpm** [comment]
> @rapgodnpm I observed in the build settings that you can `enable performance mode` for specific branch..
> It gives a Docker image on a host with 4 vCPU, 7GB memory.

Already tried that, had the same issue. From what I’ve read in the docs the performance mode just increases the max cache time from a few minutes to a day. Still a 1024mb lambda function was used. I think that docker image that you mention is for the build env. I do remember when the build was in progress that it mentions that kind of configurarion

**Comment by IvanCaceres** [comment]
Is there any progress on this issue? Cold starts are a serious performance issue for Next.js SSR users on Amplify Hosting. Is there any confirmation that using the Nextjs 13 app folder improves performance versus the older pages directory?

**Comment by mr-rpl** [comment]
@IvanCaceres - app dir definitely helps with cold start -- but introduces a whole new set of issues :)

**Comment by jdpst** [comment]
@rapgodnpm what memory would you suggest?

@mr-rpl We ended up using open-next to package the NextJS build output and deploying it on Lambda ourselves. Cold starts remain–so it's probably not an Amplify issue specifically–but with more control over the infra we can do things like enable provisioned concurrency. It still works out substantially less expensive than Fargate, which is where we're coming from.

**Comment by rapgodnpm** [comment]
> @rapgodnpm what memory would you suggest?
> 
> @mr-rpl We ended up using open-next to package the NextJS build output and deploying it on Lambda ourselves. Cold starts remain–so it's probably not an Amplify issue specifically–but with more control over the infra we can do things like enable provisioned concurrency. It still works out substantially less expensive than Fargate, which is where we're coming from.

I don’t know. I would need to test it and see which produces a smaller cold start but I can’t really do that since amplify has no setting for this

**Comment by jbreemhaar** [comment]
Experiencing this for three amplify hosting apps I've migrated from WEB_DYNAMIC to WEB_COMPUTE two days ago. TTFB is spiking all over the place since then. The apps still on WEB_DYNAMIC are having no problems with server response. 

![image](https://user-images.githubusercontent.com/15439317/224959706-106058f9-fabb-40bd-8b8e-d920c4fed47a.png)

**Comment by soplan** [comment]
Same issue for us. Will switch to Vercel because this is unacceptable.

**Comment by jbreemhaar** [comment]
@hloriii Any update on this? This has now been an issue for a couple of months.

**Comment by AdminHipoo** [comment]
same thing here, on dev environment we dont have problem we can wait, but our users on prod can't.... waiting for this issue to be resolve pls update us @hloriii

**Comment by danshev** [comment]
Can we get confirmation that this is being worked / a status update? Will need to investigate other hosting providers if there is no solve around the corner.

**Comment by choskas** [comment]
A little update about this issue, i test enabling Route 53 health check (as posted by @talaikis ) and works!. I will wait on an update on this issue to remove it but in the mean time i recommend it

**Comment by Nguyen-Huu-Huan** [comment]
I enabled the health check but still got the cold start

**Comment by Jay2113** [comment]
Hey everyone 👋 , thank you for your continued patience.

We are actively investigating and are working on narrowing down the root cause of the elevated latencies (high TTFB) with Compute apps. Please rest assured that this is our highest priority and we will keep you posted with any updates.

Apologies for the inconvenience caused due to this behavior with Compute apps.

**Comment by afern247** [comment]
Waiting for this as well... my web feels like it's loading the whole internet at start up.

**Comment by colin-chadwick** [comment]
Need an update on this as well. Otherwise, we’ll have to switch to Vercel again. Such a high TTFB is unacceptable.

**Comment by soplan** [comment]
that's funny. Vercel also has cold start issues. Not sure why you believe this is only applicable to AWS. Vercel uses AWS for hosting.

Either way, use route 53 health checks and gone are your cold start issues. At least for us it is.

**Comment by kachkaev** [comment]
@soplan how often do you run those checks? Once in how many minutes?

**Comment by vafPER** [comment]
Any update on this? @Jay2113

**Comment by RenzhiLi** [comment]
We tried to migrate the app back to the WEB_DYNAMIC platform and it works. Could migrate back to the new Web Compute platform when this issue is fixed.

AWS CLI Command:
`aws amplify update-app --app-id <your-app-id> --platform WEB_DYNAMIC`

**Comment by afern247** [comment]
This is simply unacceptable... What is the status on this?!

![image](https://github.com/aws-amplify/amplify-hosting/assets/34192856/7dd101b6-cd6e-47a4-b17f-1bbc20fb1496)

**Comment by swaminator** [comment]
@colin-chadwick @afern247 can you share your appIDs please?

**Comment by afern247** [comment]
> @colin-chadwick @afern247 can you share your appIDs please?

It's `d3fooq4aiahxc0`

**Comment by colin-chadwick** [comment]
Mine is d16xb97oi6wxj4

**Comment by michrome** [comment]
Thank you for your patience here. We have recently deployed improvements to the startup time for Next.js 12 and 13 with have larger numbers of dependencies. The improvements are automatically applied during branch builds.

We are working on improving the performance of apps with large/many static assets and apps that use next/image. We will deploy these improvements in the coming months.

**Comment by michrome** [comment]
Hey @colin-chadwick you might want to revise your `cache-control` header. Right now I see it's returning `private, no-cache, no-store, max-age=0, must-revalidate`, missing opportunities to cache at the client, CDN and app server.

**Comment by colin-chadwick** [comment]
Hey @michrome, thanks for letting me know! Setting up a health check that regularly visits the page to keep it warm definitely helped as well. Do you have any guides to setup these headers? I deployed the site on Amplify without making any further adjustments. It seems like there are still some performance options I’m missing out on.

**Comment by soplan** [comment]
> @soplan how often do you run those checks? Once in how many minutes?
> 
> PS: I experienced similar issues on Vercel before, it was to do with heavy lambda functions taking time to warm up: https://github.com/orgs/vercel/discussions/496
> 
> As a workaround, we did this:
> 
> * [.github/workflows/warm-up-vercel.yml](https://github.com/blockprotocol/blockprotocol/blob/530a683a2622a4e64211242c5adb1daac61e9c31/.github/workflows/warm-up-vercel.yml)
> * [.github/actions/warm-up-vercel/action.yml](https://github.com/blockprotocol/blockprotocol/blob/530a683a2622a4e64211242c5adb1daac61e9c31/.github/actions/warm-up-vercel/action.yml)
> 
> I’d like to do something similar against an Amplify project, so I wonder what frequency is enough. If an Amplify app is kept warm all the time, how does this affect billing?

you only get 2 options when configuring health checks in route 53. Just keep it default. I believe it's every 30 sec or 10 sec?

Either way, it affects your billing by 1 USD per month as each health check costs you 1 USD. it's a bargain.

**Comment by afern247** [comment]
> Thank you for your patience here. We have recently deployed improvements to the startup time for Next.js 12 and 13 that have larger numbers of dependencies. The improvements are automatically applied during branch builds.
> 
> We are working on improving the performance of apps with large/many static assets and apps that use next/image. We will deploy these improvements in the coming months.

It seemed to have improved, not the best performance but at least is not taking 6 seconds now... Until it's fixed I'm fine with it under 1 sec. Thank you.

**Comment by ekaterina4952** [comment]
> Hey @colin-chadwick you might want to revise your `cache-control` header. Right now I see it's returning `private, no-cache, no-store, max-age=0, must-revalidate`, missing opportunities to cache at the client, CDN and app server.

I am curious what cache setting will help when initial call happens.

**Comment by abepuentes** [comment]
To the people using route 58 as a warmup option, as far as I understand that will keep up just one lambda warm up, so when you have a couple of concurrent connection the new users will still experience cold start issues. SST let you set up a couple of warm functions to resolve this, if someone wanna try today until this is completely resolve here. Btw has anyone experiencing higher than expected building cost from amplify hosting?

**Comment by punit1108** [comment]
Need to know if someone is working on this or not? @hloriii 

Setting up Health Check eats up a whole lot of Amplify Bandwidth (as the home page of my website is around 3-4 MBs), resulting in higher bills. 
If no one is working on this, we would be better off finding some permanent solution to this.

**Comment by marcantoineveilleux** [comment]
@punit1108 on my side, I've created a very simple page that calls a dummy SSR call to make sure the health check spans a machine and not hit the next cache. This is what the health check is pinging. Works well.

**Comment by punit1108** [comment]
@marcantoineveilleux Oh, good to hear that. Very curious to know how did you manage to do that. Any resource where I can read this up?

**Comment by marcantoineveilleux** [comment]
@punit1108 

This isn't exactly what I did, but should work: https://stackoverflow.com/questions/57956476/how-to-set-up-an-endpoint-for-health-check-on-next-js

**Comment by punit1108** [comment]
@marcantoineveilleux This worked beautifully. Thanks! 

Although it's a great workaround, it still costs money for no reason, it would really be great if amplify team fixes this issue asap.

**Comment by jbreemhaar** [comment]
![image](https://github.com/aws-amplify/amplify-hosting/assets/15439317/f96d09c1-6591-4237-a29e-d3b86709c981)

Might not work for everyone, but in a Nextjs app (pages router) I've moved Amplify.configure to async clientside (except for some specific routes where I *need* to have amplify configured immediately). My TTFB dropped immediately as you can see in the screenshot. 

So basically. Everything is immediately rendered, except for everything Amplify related which get lazyloaded.
